# Global mise Configuration (~/.config/mise/mise.toml)

[tools]

# Programming Languages
python     = "latest"
ruby       = "latest"
go         = "latest"
zig        = "latest"
rust       = "latest"
nim        = "latest"
node       = "latest"

# Infrastructure & Cloud Tools
terraform  = "latest"
packer     = "latest"
kubectl    = "latest"
kubectx    = "latest"
flux2      = "latest"
helm       = "latest"
istioctl   = "latest"
tflint     = "latest"
awscli     = "latest"
