name: Test Nix-Darwin & Install Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Verify Nix Installation
        run: nix --version

      - name: Check Flake Configuration
        run: nix flake check --show-trace

      - name: Build nix-darwin configuration (dry run)
        run: nix build ".#darwinConfigurations.obsidian-flake.system"

      - name: Lint `letmecook.sh` script
        run: shellcheck letmecook.sh

      - name: Test `letmecook.sh` in a Safe Mode
        run: |
          chmod +x letmecook.sh
          ./letmecook.sh --dry-run || true