name: Test Nix-Darwin & Install Script

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual execution

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix Store
        uses: actions/cache@v4
        with:
          path: /nix/store  # Only cache store, avoid permission issues
          key: nix-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: |
          nix-env --version || echo "Nix installation failed!"
          nix profile install nixpkgs#nix

  check-flake:
    needs: setup  # Ensures setup job runs first
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Nix Is Available
        run: |
          nix-env --version || echo "Nix not found"
          nix profile install nixpkgs#nix

      - name: Check Flake Configuration
        run: |
          cd nix
          nix flake check --show-trace

  build-darwin:
    needs: check-flake
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build nix-darwin configuration (dry run)
        run: |
          cd nix
          nix build ".#darwinConfigurations.obsidian-flake.system"

  apply-darwin:
    needs: build-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply nix-darwin configuration
        run: |
          cd nix
          darwin-rebuild switch --flake .#obsidian-flake

  test-letmecook:
    needs: apply-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run `letmecook.sh` in Dry-Run Mode
        run: |
          chmod +x letmecook.sh
          ./letmecook.sh --dry-run || true