name: Test Nix-Darwin & Install Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
          mkdir -p ~/.config/nix  # Ensure the directory exists
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
          source ~/.nix-profile/etc/profile.d/nix.sh  # Load Nix immediately

      - name: Verify Nix Installation
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix --version

      - name: Check Flake Configuration
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix flake check --show-trace

      - name: Build nix-darwin configuration (dry run)
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix build ".#darwinConfigurations.obsidian-flake.system"

      - name: Lint `letmecook.sh` script
        run: shellcheck letmecook.sh

      - name: Test `letmecook.sh` in a Safe Mode
        run: |
          chmod +x letmecook.sh
          ./letmecook.sh --dry-run || true