name: CI - Test Nix-Darwin & Install Script

on:
  pull_request:
  workflow_dispatch: # Allow manual execution

jobs:
  ## ─────────────────────────────────────────────────────────────
  ## ✅ TEST NIX-DARWIN CONFIGURATION
  ## ─────────────────────────────────────────────────────────────
  test-nix-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix Store
        uses: actions/cache@v4
        with:
          path: /nix/store # Only cache store, avoid permission issues
          key: nix-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: |
          nix profile install nixpkgs#nix
          nix-env --version || echo "Nix installation failed!"

      - name: Check Flake Configuration
        run: |
          cd nix
          nix flake check --show-trace

      - name: Build nix-darwin configuration (dry run)
        run: |
          cd nix
          nix build ".#darwinConfigurations.obsidian-flake.system"

      - name: Ensure `darwin-rebuild switch` is available
        run: |
          nix profile install nixpkgs#darwin-rebuild

      - name: Apply nix-darwin configuration
        run: |
          cd nix
          darwin-rebuild switch --flake .#obsidian-flake

  ## ─────────────────────────────────────────────────────────────
  ## ✅ TEST `letmecook.sh` INSTALLATION SCRIPT ON MACOS
  ## ─────────────────────────────────────────────────────────────
  test-letmecook:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix Store
        uses: actions/cache@v4
        with:
          path: /nix/store # Only cache store, avoid permission issues
          key: nix-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: |
          nix profile install nixpkgs#nix
          nix-env --version || echo "Nix installation failed!"

      - name: Ensure Script is Executable
        run: chmod +x letmecook.sh

      - name: Run `letmecook.sh` in Dry-Run Mode
        run: |
          ./letmecook.sh --dry-run || true
